export const browserCoreExamples = [
  "rebootix browser status",
  "rebootix browser start",
  "rebootix browser stop",
  "rebootix browser tabs",
  "rebootix browser open https://example.com",
  "rebootix browser focus abcd1234",
  "rebootix browser close abcd1234",
  "rebootix browser screenshot",
  "rebootix browser screenshot --full-page",
  "rebootix browser screenshot --ref 12",
  "rebootix browser snapshot",
  "rebootix browser snapshot --format aria --limit 200",
  "rebootix browser snapshot --efficient",
  "rebootix browser snapshot --labels",
];

export const browserActionExamples = [
  "rebootix browser navigate https://example.com",
  "rebootix browser resize 1280 720",
  "rebootix browser click 12 --double",
  'rebootix browser type 23 "hello" --submit',
  "rebootix browser press Enter",
  "rebootix browser hover 44",
  "rebootix browser drag 10 11",
  "rebootix browser select 9 OptionA OptionB",
  "rebootix browser upload /tmp/file.pdf",
  'rebootix browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "rebootix browser dialog --accept",
  'rebootix browser wait --text "Done"',
  "rebootix browser evaluate --fn '(el) => el.textContent' --ref 7",
  "rebootix browser console --level error",
  "rebootix browser pdf",
];
