#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${REBOOTIX_INSTALL_E2E_IMAGE:-${REBOOTIX_INSTALL_E2E_IMAGE:-rebootix-install-e2e:local}}"
INSTALL_URL="${REBOOTIX_INSTALL_URL:-${REBOOTIX_INSTALL_URL:-https://rebootix.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
REBOOTIX_E2E_MODELS="${REBOOTIX_E2E_MODELS:-${REBOOTIX_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e REBOOTIX_INSTALL_URL="$INSTALL_URL" \
  -e REBOOTIX_INSTALL_TAG="${REBOOTIX_INSTALL_TAG:-${REBOOTIX_INSTALL_TAG:-latest}}" \
  -e REBOOTIX_E2E_MODELS="$REBOOTIX_E2E_MODELS" \
  -e REBOOTIX_INSTALL_E2E_PREVIOUS="${REBOOTIX_INSTALL_E2E_PREVIOUS:-${REBOOTIX_INSTALL_E2E_PREVIOUS:-}}" \
  -e REBOOTIX_INSTALL_E2E_SKIP_PREVIOUS="${REBOOTIX_INSTALL_E2E_SKIP_PREVIOUS:-${REBOOTIX_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
